### PR TITLE
Split up client-utils into modules so functions are h2

### PR DESCRIPTION
**Pull request by lsgunnlsgunn**
### Built-in module in client utils

Related Issue/Asana ticket: \_

Short description: \_

### Test scenarios

- description of the (manually) executed test scenarios

### Reminders (if applicable)

- [ ] I ran `pnpm install` and `pnpm test` in the root of the monorepo
      (optionally with `--filter=...package...` to exclude non-affected
      projects)
- [ ] I ran `pnpm changeset` in the root of the monorepo
- [ ] Test coverage has not decreased
- [ ] Docs have been updated to reflect changes in PR (don't forget
      docs.kadena.io)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206362614074808

### CODE REVIEW

**Comment by lsgunnlsgunn** [comment]
@javadkh2 I've been thinking about splitting up the client-utils reference section into the different modules. I just did a first pass through what the Marmalade team put together for their functions, so I thought I would take a stab at the built-in modules.
When you get a chance, can you take a look and correct my mistakes and maybe point me to some simple examples?
Not urgent, just something I've been meaning to take another crack at.

**Comment by lsgunnlsgunn** [comment]
Hi @javadkh2, I revised the client-utils library to highlight the modules. Can you take another look to. correct/clarify the use cases of the different modules, and possibly add some code snippets for the usage and examples?

**Comment by javadkh2** [comment]
> Hi @javadkh2, I revised the client-utils library to highlight the modules. Can you take another look to. correct/clarify the use cases of the different modules, and possibly add some code snippets for the usage and examples?

HI @lsgunnlsgunn that's a good improvement for sure, I need to add some code snippets to doc.

**Comment by lsgunnlsgunn** [comment]
Closing this stale PR that's failing on kode-ui and redirect errors in favor of https://github.com/kadena-community/kadena.js/pull/2518.

**Pull request closed without merging**
