### PR TITLE
Update pnpm (v7) and Node.js (>=16)

### PR DESCRIPTION
**Pull request by webpro**
## Reason:

When starting out I couldn't start anything because the project demands Node.js <= v16. I'm at Node.js v18 and v20 is also released. So I figured we should basically turn this around now: let's allow Node.js >= v16. Also we can start using pnpm v7 (had some issues with pnpm v8 we can look into later).

Closes [issue link]

## Check off the following:

- [ ] I have reviewed my changes and run the appropriate tests.
- [ ] I have have run `rush change` to add the appropriate change logs.
- [ ] I have added/edited docs.
- [ ] I have added tutorials.
- [ ] I have double checked and DEFINITELY added docs.

### CODE REVIEW

**Comment by webpro** [comment]
Tracking https://github.com/microsoft/rushstack/issues/4033 for pnpm v8

**Review by ash-vd — APPROVED** [review]

**Review by eileenmguo — APPROVED** [review]

**Comment by javadkh2** [comment]
There are some issues that arise when using pnpm 7. 
Perhaps it would be best to only update the node version to 16 at this stage

**Comment by javadkh2** [comment]
There are some issues that arise when using pnpm 7. 
Perhaps it would be best to only update the node version to 16 at this stage

**Comment by webpro** [comment]
Thanks, closing this in favor of #273.

**Pull request closed without merging**
