### PR TITLE
Prepare @kadena/kda-cli for alpha release

### PR DESCRIPTION
**Pull request by EnoF**

### CODE REVIEW

**Review by Randynamic — APPROVED** [review]

**Comment by Randynamic** [comment]
@EnoF do we still need to release this?

**Review by alber70g — COMMENTED** [review]
You probably want to add a `version-policy` to the `version-policies.json` specifically for kda-cli. 

Take a look at https://rushjs.io/pages/maintainer/publishing/#3-version-policy

**Comment by EnoF** [comment]
We don't need to release this just yet for the upcoming event. So I'm marking this PR as draft for now.

**Comment by EnoF** [comment]
Can't mark it as draft... so I'll close it for now :sweat:

**Pull request closed without merging**
