### PR TITLE
Move `.kadena/pactjs-generated` one level up, out of `node_modules`

### PR DESCRIPTION
**Pull request by webpro**
- Generated files shouldn't be hidden in `node_modules`, but be more visible instead + eligible for (different kind of) caching
- Might caused race conditions during format/build tasks

Breaking change in `tsconfig.json`:

Before:

```json
{
  "compilerOptions": {
    "types": [".kadena/pactjs-generated"]
  },
}

```

After:

```json
{
  "compilerOptions": {
    "types": []
  },
  "include": [".kadena/pactjs-generated"]
}
```

### CODE REVIEW

**Comment by alber70g** [comment]
> Note that TypeScript checks both the current dir and `node_modules` for the `types` so I expect no issues here.

With this comment you're saying that it's not a breaking change?

Can we add a check for the user that they have to add the `"include": ...` section to the `tsconfig.json` when currently the `tsconfig.json#compilerOptions.types.includes('.kadena/pactjs-generated')`

**Review by alber70g — CHANGES_REQUESTED** [review]
Instead of duplicating generated code, in both `./.kadena` and `./node_modules/.kadena/pactjs-generated`, I recommend adopting a fix-forward strategy. 

We should empower the user with the ability to designate a custom directory by adding a `--out <directory>` option into the CLI.

This approach ensures that individuals encountering issues with the `./node_modules/.kadena/pactjs-generated` package can gracefully choose to opt out, while allowing others to continue using the base functionality. 

An additional advantage is that this adjustment won't needlessly disrupt established workflows.

**Comment by Randynamic** [comment]
Why Is it a bad thing to introduce a breaking change?

**Comment by alber70g** [comment]
> Why Is it a bad thing to introduce a breaking change?

It's not, but when it's _unnecessary_ it's better to _improve_ the current state by adding a feature.

Current situation:
default output directory `./node_modules/.kadena/pactjs-generated`

New situation:
customizable output directory with `--out`, when not supplied, use the default output directory `./node_modules/.kadena/pactjs-generated`

**Comment by webpro** [comment]
The point of this PR, as described in the initial two bullet points, is getting rid of that default behavior altogether. It's not a good practice and it's most likely causing race conditions. So a breaking change is necessary. Adding a feature would make the situation even worse.

**Comment by alber70g** [comment]
> The point of this PR, as described in the initial two bullet points, is getting rid of that default behavior altogether. It's not a good practice and it's most likely causing race conditions. So a breaking change is necessary. Adding a feature would make the situation even worse.

I agree, a breaking change for this is necessary, and it's the right thing to do, but not right now. It doesn't benefit the community to introduce a breaking change this early in the release of 1.0.0. 

We should take the time to iron out the bugs that can be fixed in minor and patch releases, so the consumers _automatically_ enjoy them (considering that most consumers use `^` as their semver indicator), and after a while we can introduce it, with other breaking changes that we want to make, as one major version upgrade.

**Comment by Randynamic** [comment]
@alber70g when are we going to merge this one?

**Comment by Randynamic** [comment]
https://app.asana.com/0/1206899464980558/1208226679158102

**Pull request closed without merging**
