### PR TITLE
Block Explorer package added

### PR DESCRIPTION
**Pull request by johnkimarchitech**
## Reason:

Merge for Block Explorer

## Changes made (preferably with images/screenshots):

Added Block Explorer package

## Check off the following:

- [X] I have reviewed my changes and run the appropriate tests.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203141901191407

### CODE REVIEW

**Comment by alber70g** [comment]
Thank you for this contribution. Looks like a great thing to have.

A few things:
- [ ] move the project to `packages/apps` as it seems to be an app
- [ ] please convert the project to use the Rush-stack tooling (being, add it to the `rush.json`, use `heft` to build, etc)
- [ ] could you provide some context and reasoning for this Pull Request

**Review by alber70g — CHANGES_REQUESTED** [review]
Thank you for this contribution. Looks like a great thing to have.

A few things:
- [x] move the project to `packages/apps` as it seems to be an app
- [x] please convert the project to use the Rush-stack tooling (being, add it to the `rush.json`, use `heft` to build, etc. Find some information on this here: [@rushstack/heft-web-rig](https://github.com/microsoft/rushstack/tree/main/rigs/heft-web-rig#rushstackheft-web-rig) and [docs for rigs](https://rushstack.io/pages/heft/rig_packages/))
- [x] could you provide some context and reasoning for this Pull Request
- [x] remove `.idea`

**Review by Randynamic — DISMISSED** [review]

**Comment by Randynamic** [comment]
@johnkimarchitech Quick question when I run `npm start`, the project doesn't run on my machine. Can we fix that.

**Comment by Randynamic** [comment]
Created a lite version of this PR https://github.com/kadena-community/kadena.js/pull/78
This will be closed.

**Pull request closed without merging**
