### PR TITLE
Added new favicon

### PR DESCRIPTION
**Pull request by Randynamic**

### CODE REVIEW

**Comment by sanderlooijenga** [comment]
On the [deployed preview](https://tools-git-fix-tools-favicon-kadena-js.vercel.app/) I don't see the favicon, should it appear there already?

**Comment by sanderlooijenga** [comment]
> On the [deployed preview](https://tools-git-fix-tools-favicon-kadena-js.vercel.app/) I don't see the favicon, should it appear there already?

I think it should, looking at the deployed preview of an other branch; https://tools-git-feat-tools-websitetrack-and-trace-pa-300bd5-kadena-js.vercel.app/

**Comment by sstraatemans** [comment]
there is a `common/images` package in the mono repo.
there are all the icons. 
for docs we copy these to our package on build time. so we have 1 place where the favicons live.

or maybe they can be added to the react-ui?

**Comment by Randynamic** [comment]
Don't we want to have different favicons per site based on the eventual theme.
@sanderlooijenga it is weird the favicon doesn't changes indeed will look into this tomorrow

**Review by alber70g — APPROVED** [review]

**Pull request closed without merging**
