### PR TITLE
[@kadena/transfer] Module explorer

### PR DESCRIPTION
**Pull request by jessevanmuijden**

### CODE REVIEW

**Comment by nil-amrutlal-dept** [comment]
Is this PR completed? I noticed the code viewer is displayed after the list (which can be really big sometimes)

**Comment by jessevanmuijden** [comment]
@nil-amrutlal-dept not quite. I just learned that the code editor should render the contract in JavaScript, which should be updatable and executable. The UX is indeed not optimal with the editor below the list. I would prefer a detail view on a page that is separate from the list page.

**Comment by jessevanmuijden** [comment]
@nil-amrutlal-dept can you please help me get this PR merged after all?

**Comment by nil-amrutlal-dept** [comment]
Note: when we have a design for this page, the affected pages should be changed accordingly. Appart from that, everything looks good

**Review by nil-amrutlal-dept — APPROVED** [review]

**Review by nil-amrutlal-dept — APPROVED** [review]
Note: when we have a design for this page, the affected pages should be changed accordingly. Appart from that, everything looks good

**Pull request merged**
