### PR TITLE
Update README with KadenaJS Reasoning and Package List/Descriptions

### PR DESCRIPTION
**Pull request by Luzzotica**
## Reason:

It was ludicrously hard to find a source of information that listed off all of the libraries (And planned libraries) in KadenaJS along with a description of what each one did.

I finally stumbled on the Contributions markdown file.

I just copied the data from there into the readme. The Readme definitely deserves to have that information. I'm not sure if makes sense in the contributions file.

## Changes made (preferably with images/screenshots):

Add kadena js package list and descriptions to the main README so people can easily see what each piece does and find what they need faster.

## Check off the following:

- [x] I have reviewed my changes and run the appropriate tests.
- [x] I have have run `rush change` to add the appropriate change logs.
- [x] I have added/edited docs.
- [x] I have added tutorials.
- [x] I have double checked and DEFINITELY added docs.

### CODE REVIEW

**Comment by Randynamic** [comment]
https://github.com/kadena-community/kadena.js/issues/42 <-- list

**Review by Randynamic — APPROVED** [review]

**Review by alber70g — COMMENTED** [review]
I’m OOO this week but I really like what you did here. Before we merge this we need to define what we want to add in the readme.

I would like something similar to this table under “Published Packages” https://github.com/microsoft/rushstack/blob/main/README.md

Let me know your thoughts

**Review by nillo — APPROVED** [review]

**Comment by Luzzotica** [comment]
> I’m OOO this week but I really like what you did here. Before we merge this we need to define what we want to add in the readme.
> 
> I would like something similar to this table under “Published Packages” https://github.com/microsoft/rushstack/blob/main/README.md
> 
> Let me know your thoughts

I believe adding all of the links would be very beneficial, and be a great improvement to the changes I made, yes.
I'm all for it. 
Would you like me to do it?

I believe that either way though, these changes are already an improvement to the repo itself, and should be merged.
Incremental changes. If everyone feels this is already an improvement, let's merge it.
Then we can "define what we want to add in the readme". Glad this PR got the conversation started.

**Review by Randynamic — APPROVED** [review]
Agreed I'll merge this. It would be great if you want to help us out on that part. Let's keep the discussion going.

**Comment by Randynamic** [comment]
@Luzzotica, we only need a quick `rush change` can you add this so we can merge?

**Pull request merged**
